#ifndef KEYSEQUENCE_WIDGET_SHARED_HPP
#define KEYSEQUENCE_WIDGET_SHARED_HPP

#include <QtGlobal>

#ifdef KEYSEQUENCE_WIDGET_SHARED
    #ifdef KEYSEQUENCE_WIDGET_BUILDING_SHARED
        #define KEYSEQUENCE_WIDGET_SHARED_EXPORT Q_DECL_EXPORT
    #else
        #define KEYSEQUENCE_WIDGET_SHARED_EXPORT Q_DECL_IMPORT
    #endif
#else
    #define KEYSEQUENCE_WIDGET_SHARED_EXPORT
#endif

#endif
